# Generated by Django 3.2.10 on 2023-06-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Discription', models.CharField(blank=True, max_length=100, null=True)),
                ('C_Image', models.ImageField(blank=True, null=True, upload_to='category')),
            ],
        ),
    ]
