# Generated by Django 3.2.10 on 2023-06-17 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0002_productdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdb',
            old_name='Discription',
            new_name='Discriptions',
        ),
    ]
