# Generated by Django 3.2.10 on 2023-06-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0003_rename_discription_productdb_discriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='Discriptions',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
