# Generated by Django 3.2.10 on 2023-06-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0004_alter_productdb_discriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Number', models.IntegerField(blank=True, null=True)),
                ('Message', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
