# Generated by Django 3.2.10 on 2023-06-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0008_auto_20230621_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdb',
            name='P_Image2',
        ),
    ]
