# Generated by Django 3.2.10 on 2023-06-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0009_remove_productdb_p_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='P_Image2',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
    ]
