# Generated by Django 3.2.10 on 2023-06-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PickupLocation', models.CharField(blank=True, max_length=200, null=True)),
                ('DropoffLocation', models.CharField(blank=True, max_length=100, null=True)),
                ('PickUpDate', models.DateField(blank=True, max_length=10, null=True)),
                ('PickUpTime', models.TimeField(blank=True, null=True)),
                ('No_days', models.IntegerField(blank=True, null=True)),
                ('Totalprice', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
