# Generated by Django 3.2.10 on 2023-06-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rentapp', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='PickUpDate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
