# Generated by Django 3.2.10 on 2023-06-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rentapp', '0003_alter_booking_pickupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='User',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
