# Generated by Django 3.2.10 on 2023-06-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rentapp', '0004_booking_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(blank=True, max_length=122, null=True)),
                ('sname', models.CharField(blank=True, max_length=122, null=True)),
                ('Country', models.CharField(blank=True, max_length=122, null=True)),
                ('Address', models.CharField(blank=True, max_length=122, null=True)),
                ('City', models.CharField(blank=True, max_length=122, null=True)),
                ('Pin', models.IntegerField(blank=True, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=122, null=True)),
                ('Payment', models.CharField(blank=True, max_length=122, null=True)),
            ],
        ),
    ]
