# Generated by Django 3.2.10 on 2023-06-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rentapp', '0006_booking_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='P_image',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
    ]
