# Generated by Django 3.2.10 on 2023-06-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rentapp', '0007_payment_p_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='P_image',
        ),
        migrations.AddField(
            model_name='booking',
            name='P_image',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
    ]
