# Generated by Django 3.2.10 on 2023-06-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rentapp', '0008_auto_20230701_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
